### ISSUE TITLE
Project Name Validator not working correctly

### ISSUE THREAD

**Issue by sbindman** [Cadasta/ckanext-project#4]
If a user tries to create a project without a title the old error is still coming up to update the URL.  However, if an existing title is entered, the error pops up correctly.

<img width="1015" alt="screen shot 2015-10-02 at 4 04 07 pm" src="https://cloud.githubusercontent.com/assets/10539483/10259849/303a1540-6922-11e5-9005-dc2fb9f9a77b.png">

I am looking at the forked repo, commit: 7b849c3434c33481337579c452a4c6a45661efee

**Comment by joetsoi** [comment]
https://github.com/okfn/ckanext-project/commit/3fb2f108487319a5cf6f1d21329a81103c3bfff8 fixed, not_missing just needed to be moved to title from name.

**Comment by joetsoi** [comment]
@rgwozdz ,  a397738 should also fix the issues you sent me yesterday evening.

CKAN's default is to allow you to enter a title and it will suggest a name(url) based upon that and allow the user to adjust it if they wish. Since we don't want that in ckanext-project I've rejigged it all to work so evertything is created from the title instead of the otherway round.

Basically CKAN has some javascript that automatically fills out the name from the title. The screenshot you sent me is a bug where the it doesn't update the name from the title.

So I've removed all that javascript and the name is slugifyed from the title during validation. If name is not provided, it is the slugifyed title

if the name is provided it becomes slugified (probably in the api creation use case)
