### ISSUE TITLE
Delete incomplete project/org throws 404

### ISSUE THREAD

**Issue by galenerickson** [Cadasta/ckanext-project#54]
Steps:
Click create project (or organization) button
Begin adding fields
Click the "delete" button BEFORE saving the project/org.

Expected result:
Project/org is deleted and user  is redirected to the project or organizations list

Actual Result:
User sees 404 Error

**Comment by rgwozdz** [comment]
Most likely because you are trying to delete a project that is not yet in the system.

R

On Oct 26, 2015, at 5:01 PM, galenerickson <notifications@github.com<mailto:notifications@github.com>> wrote:


Steps:
Click create project (or organization) button
Begin adding fields
Click the "delete" button BEFORE saving the project/org.

Expected result:
Project/org is deleted and user is redirected to the project or organizations list

Actual Result:
User sees 404 Error

**Comment by thebigspoon** [comment]
now you can't delete midway through a create. fixed and deployed to staging
