### ISSUE TITLE
createProjectParcel unexpected character

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#59]
The proxy endpoint for `createProjectParcell` and the developing PR for #50 has an outstanding bug where PostGIS cannot create the parcel because of an error `"unexpected character (at offset 0)"`.

However, it doesn't seem to be the geometry because the escaped string that NodeJS gets works fine:
```sql
SELECT * FROM ST_SetSRID(ST_GeomFromGeoJSON($anystr${'type': 'Polygon', 'coordinates': [[[-122.64999389648438, 48.824486510845475], [-122.64999389648438, 48.866285108547], [-122.52399444580077, 48.866285108547], [-122.52399444580077, 48.824486510845475], [-122.64999389648438, 48.824486510845475]]]}$anystr$),4326);
```

**Comment by rgwozdz** [comment]
Could it be that HTML element in the middle of the geometry array?


<
 span class="pl-c1">



On Oct 27, 2015, at 7:04 PM, sudobangbang <notifications@github.com<mailto:notifications@github.com>> wrote:


the developing PR for #50<https://github.com/Cadasta/ckanext-project/issues/50> has an outstanding bug where PostGIS cannot create the parcel because of an error "unexpected character (at offset 0)".

However, it doesn't seem to be the geometry because the escaped string that NodeJS gets works fine:

ST_SetSRID(ST_GeomFromGeoJSON($anystr${'type': 'Polygon', 'coordinates': [[[-122.64999389648438, 48.824486510845475], [-122.64999389648438, 48.866285108547], [-122.52399444580077, 48.866285108547], [-122.52399444580077, <
 span class="pl-c1">48.824486510845475], [-122.64999389648438, 48.824486510845475]]]}$anystr$),4326);

**Comment by thebigspoon** [comment]
@rgwozdz: that's hilarious! but alas, no it's not that

**Comment by thebigspoon** [comment]
this one isn't working either

```sql
SELECT * FROM ST_SetSRID(ST_GeomFromGeoJSON($anystr${'type': u'Polygon', 'coordinates': [[[-132.890625, 58.63121664342478], [-132.890625, 58.99531118795094], [-127.265625, 58.99531118795094], [-127.265625, 58.63121664342478], [-132.890625, 58.63121664342478]]]}$anystr$),4326);
```

**Comment by thebigspoon** [comment]
haha, we're in business!

**Comment by danielduhh** [comment]
@thebigspoon what was the solution!!???

**Comment by thebigspoon** [comment]
@danielduhh: Python was first casting it to a string and then recasting it to a JSON string and it was screwing my life up
